dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-11/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: bXk6//Yb9R2FMafs3xtLxyGodpgjuUIITxY3umUFuEyctqcVztPcrirT7NdMKn5DuMALcWY8KWE1jR1GvcT5WmsFQIs85TCpaOEWDRQeqLp3fnzguGMlXAuWF/05j9/euWIvd/dx/k37iRUjosHNfiKULqDCmjXrSAlaka7v63djUl+vW3/cFrfOEJiIW40df3/OsUkjiQV+OfKqt7AU3EZkYrrbodmaAwXSONao1o+X64MUbewASP3UeJJMI0iq2inf/GiAHOfwBtf5gHGyFl1u8iZa3lF6Z9LeTp3ilON+5K39QM+prQJPWh7AKF0lUwRX9QdtnzVx7gixn7RFyJUZ4YP/+O1x+ZCadpygULzE2rZa3Wons077aVM27nQCO3T1AC01NXxiObXnenHtTGkyxeLdiEjpK4haHsHJtvIAKIc0KoGVH274kdaDSGwEKYZaWI25mZbdpQEeS+QXkFbTfw2h25aO6btoUCCDYl/RSU/rr9meHAahuOs5U4JDAFqrLvWxDfDcOyqOKpfzqCDo0qrY+5SU80FjQsB2xzJd4+mfoBR99eM4qG5XYYU6wZCDsx/0DYDbhBN/0W/j1vyY4PWmicGqh2NyQiX1+fowuNvZZf4ozjavvzkAgXp1ZtWlJT6SHnCusI7+uQ28pzqcXdPPkqEI2ZufAQK9svo=
